# Anydesk（仅 full/studio，ENABLE_ANYDESK 默认 true，端口 7070）
[program:anydesk]
command=/usr/local/bin/dwc-if ENABLE_ANYDESK /usr/local/bin/dwc-anydesk
autostart=true
autorestart=true
startretries=3
priority=40
stdout_logfile=/config/logs/anydesk.log
stderr_logfile=/config/logs/anydesk.err.log
