# Tor 匿名上网（tor 镜像，端口 9050/9051，SOCKS5 代理）
; ENABLE_TOR 默认 true
[program:tor]
command=/usr/local/bin/dwc-if ENABLE_TOR /usr/local/bin/dwc-tor
autostart=true
autorestart=true
startretries=3
priority=20
stdout_logfile=/config/logs/tor.log
stderr_logfile=/config/logs/tor.err.log
